openapi: 3.0.3
info:
  title: .
  description:
    <h1>Your session has expired.</h1>
    <h1>Please log in to continue.</h1>
    <h1><a href="https://example.com">Log in</a>
  version: Security

paths:
  /:
    get:
      summary: .
      description: .
      responses:
        '200':
          description: .
